### PR TITLE
Make release file only a single file

### PR DESCRIPTION
**Pull request by markjm**
This will enable `yarn set version` command to work correctly by just substituting in the release file for midgard-yarn

### CODE REVIEW

**Review by VincentBailly — APPROVED** [review]
LGTM, feel free to merge and release

**Comment by layershifter** [comment]
@markjm @VincentBailly can you please update PR's description to include how I can get `yarn.js` to put it into `.yarn/releases/yarn.js`?

**Comment by markjm** [comment]
@layershifter  there isnt a great way to do this. I had filed an issue on yarn (unforked) to support using `yarn policies set-version` to arbitrary package at a URL, but I think it was shut down. Instead, i just did it manually by adding the yarn-path variable to yarnrc and copying in my version of yarn to the right path.

Can also just run `yarn policies set-version 1.13.0` to do all the setup then just update the yarn.js generated with the contents of this forked package version (just unzip the npm package of midgard-yarn)

https://classic.yarnpkg.com/en/docs/cli/policies/

**Comment by layershifter** [comment]
@markjm thanks!

> and copying in my version of yarn to the right path.

The last question is how can I get this artifact? Should I clone this repo and build? Or is it published somewhere?

**Comment by markjm** [comment]
You can simply download the tarball of this package (or yarn add midgard-yarn in a temp project) and grab `lib/cli.js` and move it to wherever you want

**Pull request merged**
